services:
  auth_api:
    image: authapi:latest
    deploy:
      replicas: 2
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - loadbalancing
      - sqlserver-network
 
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "82:80"
    depends_on:
      - auth_api
    networks:
      - loadbalancing

  sqlserver: 
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Strong!Passw0rd"
    ports:
      - "1433:1433"
    networks:
      - sqlserver-network


networks: 
  loadbalancing:
    driver: bridge
  sqlserver-network: