services:
  # Auth Service
  auth_service:
    container_name: auth_service
    image: auth_service
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8091:8080"
    depends_on:
      - auth_sqlserver
    networks:
      - auth_sqlserver_network

  auth_sqlserver:
    container_name: auth_sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1*
    ports:
      - "1433:1433"
    networks:
      - auth_sqlserver_network

  # Offices Service
  offices_service:
    image: offices_service
    container_name: offices_service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8089:8080"
    depends_on:
      - offices_mongo
    networks:
      - messaging_network
      - offices_network
      # - cache_network

  offices_mongo:
     image: mongo
     container_name: offices_mongo
     restart: always
     environment:
        - MONGO_INITDB_DATABASE=OfficesServiceDB
     ports:
       - "27017:27017"
     volumes:
       - mongo_data:/data/db
     networks:
      - offices_network


  # offices_redis:
  #    image: redis:latest
  #    container_name: offices_redis
  #    ports:
  #      - "6379:6379"
  #    networks:
  #      - cache_network
  #    volumes:
  #      - mongo_data:/data/db

  # Documents Service
  documents_service:
    container_name: documents_service
    image: documents_service 
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8087:8080"
    depends_on:
      - documents_sqlserver     
      - documents_azurite
      - rabbitmq
    networks:
      - documents_network
      - messaging_network
    restart: always

  documents_sqlserver:
    container_name: documents_sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1*
    ports:
      - "1434:1433"
    networks:
      - documents_network

  documents_azurite:
    container_name: documents_azurite
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - "10000:10000"
    networks:
      - documents_network

#   RabbitMQ 
  rabbitmq:
     image: rabbitmq:3-management
     container_name: rabbitmq
     environment:
       RABBITMQ_DEFAULT_USER: guest
       RABBITMQ_DEFAULT_PASS: guest
     ports:
       - "5672:5672"
       - "15672:15672"
     networks:
       - messaging_network

volumes:
  mongo_data:

networks:
  # auth_sqlserver_network:
  #   driver: bridge
  documents_network:
    driver: bridge
  messaging_network:
    driver: bridge
  offices_network:
    driver: bridge
  # cache_network:
  #   driver: bridge
